name: Rust Text

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfontconfig1-dev
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        mkdir -p test
        cargo test --features test --release -- --nocapture
    - name: Push images to benchmarks branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -B benchmarks
        mkdir -p images
        cp test/*.png images/
        git add images/*.png
        git add README.md
        git commit -m "Set benchmark result image"
        git push -f origin benchmarks